[package]
name = "auth"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
argon2 = "0.5.2"
getrandom = { version = "0.2.11", features = ["js"] }
password-hash = { version = "0.5.0", features = ["getrandom"] }
wasm-bindgen = "0.2.89"
